# Site settings
title: Panama.wtf
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Un blog sur le Panama vu par des européens.
  A blog about Panama from an European perspective.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: yga
github_username:  hmallet

# Build settings
markdown: kramdown
