# Site settings
title: panama.wtf
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Un blog sur le Panama vu par des européens.
  A blog about Panama from an European perspective.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: yga
github_username:  hmallet
permalink: /title/

# Build settings
markdown: kramdown

# Gestion multilingue
defaults:
  -
    scope:
      path: _posts/en
    values:
      layout: default
      lang: en
  -
    scope:
      path: _posts/fr
    values:
      layout: default
      lang: fr
  -
    scope:
      path: _posts/hu
    values:
      layout: default
      lang: hu
